### ISSUE TITLE
'Entity' class default constructor logic

### ISSUE THREAD

**Issue by Alabuta** [BAntDit/enttx#5]
There is no need to define custom default constructor like this

```cpp
Entity()
      : id_{ std::numeric_limits<uint64_t>::max() }
    {}
```

Way better for interface if you replace it to

```cpp
class Entity {
public:
    Entity() noexcept = default;

private:
    uint64_t id_{ std::numeric_limits<uint64_t>::max() };
};
```

**Comment by BAntDit** [comment]
It makes no sense. They are both default constructible and they are **not** trivially default constructible in both cases.
